sudo: required
dist: trusty

language: haxe

haxe:
 - "4.0.0-rc.1"

install:
 - haxelib dev ghostlib .

script:
 - haxe test.hxml

deploy:
 - provider: script
   haxe: "4.0.0-rc.1"
   script: bash ./release_haxelib.sh $HAXELIB_PWD
   on:
    tags: true